# Generated by Django 6.0.6 on 2026-07-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_category_expense_created_by_expense_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='splits_owed', to='expenses.member'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together={('expense', 'member')},
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='user',
        ),
    ]
